---
- name: add mysql group
  ansible.builtin.group:
    name: mysql
    state: present

- name: add mysql user
  ansible.builtin.user:
    name: mysql
    group: mysql

- name: download mariadb server "{{ mariadb_version }}" and untar 
  ansible.builtin.unarchive:
    src: "https://archive.mariadb.org/mariadb-{{ mariadb_version }}/bintar-linux-systemd-x86_64/mariadb-{{ mariadb_version }}-linux-systemd-x86_64.tar.gz"
    dest: /usr/local/
    remote_src: yes

- name: Create a symbolic link mysql
  ansible.builtin.file:
    src: "/usr/local/mariadb-{{ mariadb_version }}-linux-systemd-x86_64"
    dest: /usr/local/mysql
    state: link

- name: add mariadb to path
  ansible.builtin.template:
    src: templates/mysql.sh.j2
    dest: /etc/profile.d/mysql.sh
    owner: root
    group: root
    #mode: '0755'
    mode: '0644'

- name: add my.cnf
  ansible.builtin.template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: '0644'

- name: mysql logg dir
  ansible.builtin.file:
    path: /var/log/mysql
    owner: mysql
    group: mysql
    state: directory
    recurse: yes
    mode: '0644'

- name: mysql data dir
  ansible.builtin.file:
    path: /var/lib/mysql
    owner: mysql
    group: mysql
    state: directory
    recurse: yes
    mode: '0755'

- name: install db mariadb
  command: /usr/local/mysql/scripts/mysql_install_db

- name: copy mariadb systemd service
  ansible.builtin.copy:
    src: /usr/local/mysql/support-files/systemd/mariadb.service
    dest: /usr/lib/systemd/system/mariadb.service
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- name: start, enable, daemon reload mariadb servies
  ansible.builtin.systemd:
    name: mariadb
    daemon_reload: yes
    enabled: yes
    state: started

