---
- name: Install mysql python package
  ansible.builtin.package:
    name: "{{ mysql_python_package_debian }}"
    state: present


- name: Install libncurses5 for mysql client
  ansible.builtin.package:
    name: libncurses5
    state: present


    
